#!/bin/bash

#One param not mandatory, either 'DEBUG', 'INFO', or '--delay'
param=$1

#manual command : sudo python ebirdsv2.py -v

if [ $# -gt 0 ] ; then
#TODO to check if the ampersand is mandatory
  if [ $param == "--delay" ] ; then
    sleep 120
    python3 ebirdsIO.py &
  else
    python3 ebirdsIO.py $param &
  fi
else
  python3 ebirdsIO.py &
fi
